// @ts-nocheck
import * as __fd_glob_50 from "../docs/modules/sherlock/schema/prisma-schema.md?collection=docs"
import * as __fd_glob_49 from "../docs/modules/sherlock/schema/entity-relationships.md?collection=docs"
import * as __fd_glob_48 from "../docs/modules/sherlock/schema/design-decisions.md?collection=docs"
import * as __fd_glob_47 from "../docs/modules/sherlock/roadmap/implementation-phases.md?collection=docs"
import * as __fd_glob_46 from "../docs/modules/sherlock/integrations/yurest.md?collection=docs"
import * as __fd_glob_45 from "../docs/modules/sherlock/integrations/gstock.md?collection=docs"
import * as __fd_glob_44 from "../docs/modules/sherlock/integrations/gstock-sync-pipeline.md?collection=docs"
import * as __fd_glob_43 from "../docs/modules/sherlock/analysis/yurest.md?collection=docs"
import * as __fd_glob_42 from "../docs/modules/sherlock/analysis/gstock.md?collection=docs"
import * as __fd_glob_41 from "../docs/modules/sherlock/analysis/comparison.md?collection=docs"
import * as __fd_glob_40 from "../docs/modules/projects/tasks/task-lists.md?collection=docs"
import * as __fd_glob_39 from "../docs/modules/projects/tasks/task-details.md?collection=docs"
import * as __fd_glob_38 from "../docs/modules/sherlock/README.md?collection=docs"
import * as __fd_glob_37 from "../docs/modules/sherlock/index.md?collection=docs"
import * as __fd_glob_36 from "../docs/modules/atc/rag-pipeline.md?collection=docs"
import * as __fd_glob_35 from "../docs/modules/atc/operations-weather.md?collection=docs"
import * as __fd_glob_34 from "../docs/modules/atc/operations-incidents.md?collection=docs"
import * as __fd_glob_33 from "../docs/modules/atc/knowledge-base.md?collection=docs"
import * as __fd_glob_32 from "../docs/modules/atc/index.md?collection=docs"
import * as __fd_glob_31 from "../docs/modules/atc/email-classification.md?collection=docs"
import * as __fd_glob_30 from "../docs/modules/notifications/integration.md?collection=docs"
import * as __fd_glob_29 from "../docs/modules/notifications/index.md?collection=docs"
import * as __fd_glob_28 from "../docs/modules/reports/index.md?collection=docs"
import * as __fd_glob_27 from "../docs/modules/admin/rbac.md?collection=docs"
import * as __fd_glob_26 from "../docs/modules/admin/index.md?collection=docs"
import * as __fd_glob_25 from "../docs/capabilities/ai-assistant/usage-tracking.md?collection=docs"
import * as __fd_glob_24 from "../docs/capabilities/ai-assistant/groq-integration.md?collection=docs"
import * as __fd_glob_23 from "../docs/capabilities/ai-assistant/gemini-integration.md?collection=docs"
import * as __fd_glob_22 from "../docs/capabilities/ai-assistant/chat-agent.md?collection=docs"
import * as __fd_glob_21 from "../docs/capabilities/ai-assistant/architecture.md?collection=docs"
import * as __fd_glob_20 from "../docs/guides/voice-commands.md?collection=docs"
import * as __fd_glob_19 from "../docs/guides/testing.md?collection=docs"
import * as __fd_glob_18 from "../docs/guides/estimation-standard.md?collection=docs"
import * as __fd_glob_17 from "../docs/guides/deployment.md?collection=docs"
import * as __fd_glob_16 from "../docs/guides/ai-context.md?collection=docs"
import * as __fd_glob_15 from "../docs/database/seeding.md?collection=docs"
import * as __fd_glob_14 from "../docs/database/data-model.md?collection=docs"
import * as __fd_glob_13 from "../docs/architecture/voice-agent.md?collection=docs"
import * as __fd_glob_12 from "../docs/architecture/system-overview.md?collection=docs"
import * as __fd_glob_11 from "../docs/architecture/modular-monolith.md?collection=docs"
import * as __fd_glob_10 from "../docs/capabilities/internationalization.md?collection=docs"
import * as __fd_glob_9 from "../docs/capabilities/file-storage.md?collection=docs"
import * as __fd_glob_8 from "../docs/capabilities/authentication.md?collection=docs"
import * as __fd_glob_7 from "../docs/README.md?collection=docs"
import * as __fd_glob_6 from "../docs/index.mdx?collection=docs"
import { default as __fd_glob_5 } from "../docs/modules/notifications/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../docs/modules/atc/n8n-email-classification-workflow.json?collection=docs"
import { default as __fd_glob_3 } from "../docs/modules/atc/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../docs/guides/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../docs/database/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../docs/architecture/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "docs", {"architecture/meta.json": __fd_glob_0, "database/meta.json": __fd_glob_1, "guides/meta.json": __fd_glob_2, "modules/atc/meta.json": __fd_glob_3, "modules/atc/n8n-email-classification-workflow.json": __fd_glob_4, "modules/notifications/meta.json": __fd_glob_5, }, {"index.mdx": __fd_glob_6, "README.md": __fd_glob_7, "capabilities/authentication.md": __fd_glob_8, "capabilities/file-storage.md": __fd_glob_9, "capabilities/internationalization.md": __fd_glob_10, "architecture/modular-monolith.md": __fd_glob_11, "architecture/system-overview.md": __fd_glob_12, "architecture/voice-agent.md": __fd_glob_13, "database/data-model.md": __fd_glob_14, "database/seeding.md": __fd_glob_15, "guides/ai-context.md": __fd_glob_16, "guides/deployment.md": __fd_glob_17, "guides/estimation-standard.md": __fd_glob_18, "guides/testing.md": __fd_glob_19, "guides/voice-commands.md": __fd_glob_20, "capabilities/ai-assistant/architecture.md": __fd_glob_21, "capabilities/ai-assistant/chat-agent.md": __fd_glob_22, "capabilities/ai-assistant/gemini-integration.md": __fd_glob_23, "capabilities/ai-assistant/groq-integration.md": __fd_glob_24, "capabilities/ai-assistant/usage-tracking.md": __fd_glob_25, "modules/admin/index.md": __fd_glob_26, "modules/admin/rbac.md": __fd_glob_27, "modules/reports/index.md": __fd_glob_28, "modules/notifications/index.md": __fd_glob_29, "modules/notifications/integration.md": __fd_glob_30, "modules/atc/email-classification.md": __fd_glob_31, "modules/atc/index.md": __fd_glob_32, "modules/atc/knowledge-base.md": __fd_glob_33, "modules/atc/operations-incidents.md": __fd_glob_34, "modules/atc/operations-weather.md": __fd_glob_35, "modules/atc/rag-pipeline.md": __fd_glob_36, "modules/sherlock/index.md": __fd_glob_37, "modules/sherlock/README.md": __fd_glob_38, "modules/projects/tasks/task-details.md": __fd_glob_39, "modules/projects/tasks/task-lists.md": __fd_glob_40, "modules/sherlock/analysis/comparison.md": __fd_glob_41, "modules/sherlock/analysis/gstock.md": __fd_glob_42, "modules/sherlock/analysis/yurest.md": __fd_glob_43, "modules/sherlock/integrations/gstock-sync-pipeline.md": __fd_glob_44, "modules/sherlock/integrations/gstock.md": __fd_glob_45, "modules/sherlock/integrations/yurest.md": __fd_glob_46, "modules/sherlock/roadmap/implementation-phases.md": __fd_glob_47, "modules/sherlock/schema/design-decisions.md": __fd_glob_48, "modules/sherlock/schema/entity-relationships.md": __fd_glob_49, "modules/sherlock/schema/prisma-schema.md": __fd_glob_50, });