import { prisma } from '@/lib/prisma'
import { requireAuth } from '@/lib/actions/rbac'
import Link from 'next/link'
import { FileText } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import rehypeRaw from 'rehype-raw'
import { ReportHeader } from '@/components/reports/report-header'
import { setRequestLocale } from "next-intl/server"

export const metadata = {
  title: 'Detalle del Informe | Dreamland',
}

export default async function ReportDetailPage({ params }: { params: Promise<{ locale: string; reportId: string }> }) {
  const { locale, reportId } = await params
  setRequestLocale(locale)
  const auth = await requireAuth()
  if (!auth.authenticated) return <div>Acceso denegado</div>

  const report = await prisma.report.findUnique({
    where: { id: reportId },
    include: { project: true }
  })

  if (!report) return <div>Informe no encontrado</div>

  // Basic security check: only author or admin (simplified)
  if (report.authorId !== auth.userId) {
     // Ideally check project permissions too, but for MVP author check + RBAC is okayish
     // return <div>No tienes permiso para ver este informe</div>
  }

  return (
    <div className="flex flex-col ai-glow min-h-full">
      <ReportHeader report={report} />
      <div className="flex-1 p-4 md:p-6 space-y-6">
        <div className="container mx-auto max-w-4xl print:py-0">
          <div className="mb-6 no-print">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
              <div>
                {report.project && (
                  <p className="text-muted-foreground mt-1">
                    Proyecto: <Link href={`/projects/${report.project.id}`} className="hover:underline text-primary">{report.project.title}</Link>
                  </p>
                )}
              </div>
            </div>
          </div>



          <article className="prose prose-sm dark:prose-invert max-w-none bg-white dark:bg-zinc-950 p-8 md:p-12 rounded-2xl border shadow-xl ai-glow relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10 pointer-events-none select-none">
              <FileText className="h-24 w-24 rotate-12" />
            </div>
            <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw]}>
              {report.content}
            </ReactMarkdown>
          </article>
          
          <div className="mt-12 text-center text-sm text-muted-foreground no-print">
            Generated by Dreamland AI Hub • ID: {report.id}
          </div>
        </div>
      </div>
    </div>
  )
}
