import { prisma } from '@/lib/prisma'
import { requireAuth } from '@/lib/actions/rbac'
import { format } from 'date-fns'
import { es } from 'date-fns/locale'
import Link from 'next/link'
import { ArrowLeft, Calendar, FileText, Printer } from 'lucide-react'
import { Button } from '@/modules/shared/ui/button'
import { Separator } from '@/modules/shared/ui/separator'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import rehypeRaw from 'rehype-raw'
import { ReportPrintButton } from '@/components/reports/report-print-button' // Client component we'll create

export const metadata = {
  title: 'Detalle del Informe | Dreamland',
}

export default async function ReportDetailPage({ params }: { params: Promise<{ reportId: string }> }) {
  const auth = await requireAuth()
  if (!auth.authenticated) return <div>Acceso denegado</div>

  const { reportId } = await params
  const report = await prisma.report.findUnique({
    where: { id: reportId },
    include: { project: true }
  })

  if (!report) return <div>Informe no encontrado</div>

  // Basic security check: only author or admin (simplified)
  if (report.authorId !== auth.userId) {
     // Ideally check project permissions too, but for MVP author check + RBAC is okayish
     // return <div>No tienes permiso para ver este informe</div>
  }

  return (
    <div className="container mx-auto py-8 max-w-4xl print:py-0">
      <div className="mb-6 no-print">
        <Button variant="ghost" asChild className="mb-4 pl-0 hover:bg-transparent hover:text-primary">
          <Link href="/reports">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Volver a Informes
          </Link>
        </Button>

        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <div className="flex items-center gap-2 text-muted-foreground mb-2">
              <span className="bg-primary/10 text-primary px-2 py-1 rounded text-xs font-semibold uppercase tracking-wide">
                {report.type}
              </span>
              <span>•</span>
              <span className="flex items-center text-sm">
                 <Calendar className="mr-1 h-3 w-3" />
                 {format(new Date(report.createdAt), "d 'de' MMMM, yyyy", { locale: es })}
              </span>
            </div>
            <h1 className="text-3xl font-bold tracking-tight text-foreground">{report.title}</h1>
            {report.project && (
              <p className="text-muted-foreground mt-1">
                Proyecto: <Link href={`/projects/${report.project.id}`} className="hover:underline text-primary">{report.project.title}</Link>
              </p>
            )}
          </div>

          <ReportPrintButton title={report.title} content={report.content} />
        </div>
      </div>

      <Separator className="my-6 no-print" />

      <article className="prose prose-sm dark:prose-invert max-w-none bg-white dark:bg-zinc-950 p-8 md:p-12 rounded-2xl border shadow-xl ai-glow relative overflow-hidden">
        <div className="absolute top-0 right-0 p-4 opacity-10 pointer-events-none select-none">
          <FileText className="h-24 w-24 rotate-12" />
        </div>
        <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw]}>
          {report.content}
        </ReactMarkdown>
      </article>
      
      <div className="mt-12 text-center text-sm text-muted-foreground no-print">
        Generated by Dreamland AI Hub • ID: {report.id}
      </div>
    </div>
  )
}
